spring:
  datasource:
    url: jdbc:mysql://localhost:3306/utn_phones?useSSL=false&serverTimezone=UTC
    username: root
    password:
  jpa:
    show-sql: true


#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password:
#  h2:
#    console:
#    enabled: true
#    path: /h2
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop
